text = {
    "First line": "Welcome to the Library Management System...",
    "Input Prompt": "Please enter a command:/ ",
    "Invalid Command": "Invalid command",
    "Exit Command": ["exit", 
                     "quit", 
                     "", 
                     " ", 
                     "\n"],
    "Student Command": ["reserve",  
                        "search"],
    "Staff Command": ["add", 
                      "delete", 
                      "edit", 
                      "search",
                      "reserve"],
    "Display Command": ["report"],
    "Help Command": ["help", 
                     "-h", 
                     "--help", 
                     "h", 
                     "?", 
                     "info"]
}